# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/bucketyaccess.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: BucketyAccess
metadata:
  name: orders-explicit
spec:
  bucketyRef:
    name: orders
  credentialsSecretName: explicit-secret
  role: ReadWrite
