apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: orders
spec:
  backend: kafka
  parameters:
    partitions: "3"
    config.retention.ms: "604800000"
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: orders-topic
