# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/bucketyaccess.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: BucketyAccess
metadata:
  name: bad-access
spec:
  bucketyRef:
    name: base
  credentialsSecretName: bad-access
  role: ReadWrite
  parameters:
    bogus: "1"
