# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: invalid
spec:
  backend: kafka
  parameters:
    bogus: "1"
  retentionPolicy: Retain
