# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-mysql.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: adopt-fresh
spec:
  backend: mysql
  name: "b_${namespace}_${name}"
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: adopt-fresh-db
