# Patch for the controller Deployment: the account password for
# ${MYSQL_BUCKETY_PASSWORD} in buckety-controller.yaml.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buckety-controller
spec:
  template:
    spec:
      containers:
      - name: controller
        env:
        - name: MYSQL_BUCKETY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-buckety
              key: password
