# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-gcs.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: templated
  labels:
    yolean.se/generation: "003"
spec:
  backend: gcs
  name: "${backend.zone}-${namespace}-${name}-v${label['yolean.se/generation']}"
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: templated-bucket
