# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-kadm.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: bad-template
spec:
  backend: kafka
  name: "${label['no.such/label']}.${name}"
  retentionPolicy: Delete
