apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: sticky-orig
spec:
  backend: kafka
  parameters:
    partitions: "1"
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: sticky-orig-topic
