# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-mysql.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: drift
spec:
  backend: mysql
  name: "b_${namespace}_${name}"
  parameters:
    characterSet: utf8mb4
    collation: utf8mb4_unicode_ci
  retentionPolicy: Delete
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/bucketyaccess.schema.json
# Explicit accesses: one would replace an implicit defaultAccess.
apiVersion: buckety.yolean.se/v1alpha1
kind: BucketyAccess
metadata:
  name: drift-rw
spec:
  bucketyRef:
    name: drift
  credentialsSecretName: drift-db
  role: ReadWrite
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/bucketyaccess.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: BucketyAccess
metadata:
  name: drift-reader
spec:
  bucketyRef:
    name: drift
  credentialsSecretName: drift-reader-db
  role: Reader
