apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: dial-tone
spec:
  backend: s3
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: dial-tone-bucket
