# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-kadm.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: adopt-fresh
spec:
  backend: kafka
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: adopt-fresh-creds
