apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: sticky-orig
spec:
  backend: s3
  retentionPolicy: Delete
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: sticky-orig-bucket
