# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-s3.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: bad-template
spec:
  backend: s3
  name: "${label['no.such/label']}-${name}"
  retentionPolicy: Delete
