# yaml-language-server: $schema=https://raw.githubusercontent.com/Yolean/buckety-controller/main/schema/buckety-gcs.schema.json
apiVersion: buckety.yolean.se/v1alpha1
kind: Buckety
metadata:
  name: shape
spec:
  backend: gcs
  retentionPolicy: Delete
  parameters:
    versioning: "true"
  defaultAccess:
    role: ReadWrite
    credentialsSecretName: shape-bucket
